title: FocusCuts
email: focuscuts@snailedit.dev
tagline: Focus on your Shortcuts
description: Get your current Focus Mode in Shortcuts, and have better access to the right Shortcuts for the Focus Mode you're currently in.
baseurl: ""
url: "https://focuscuts.com"
permalink: pretty

# Build settings
theme: minima
minima:
  skin: auto
  social_links:
    twitter: snaileditdev
timezone: Europe/London
plugins:
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
whitelist:
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
collections:
  - documentation
  - landing
  - shortcuts_actions

email_form:
  zx: 14ace68302
  zcld: 1159dc37fd887db7
  zctd: 1159dc37fd887dc4
  zc_formIx: 3z7d7f20fcd133ab46c128c2dd67200163c35765cf88f3394f74bbe5dffe3de294

# SEO
defaults:
  - scope:
      path: ""
    values:
      image: /assets/focuscuts-social.png
twitter:
  username: snaileditdev
  card: Focus on your Shortcuts

open_graph:
  image: /assets/focuscuts-social.png

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - vendor/bin